{% set major_minor = "3.7" %}
{% set version = major_minor + ".1" %}

package:
  name: cmake
  version: {{ version }}

source:
  url: https://cmake.org/files/v{{ major_minor }}/cmake-{{ version }}.tar.gz              # [not win]
  fn: cmake-{{ version }}.tar.gz                                                          # [not win]
  sha256: 449a5bce64dbd4d5b9517ebd1a1248ed197add6ad27934478976fd5f1f9330e1                # [not win]

  url: https://cmake.org/files/v{{ major_minor }}/cmake-{{ version }}-win32-x86.zip       # [win32]
  fn: cmake-{{ version }}-win32-x86.zip                                                   # [win32]
  sha256: d2ec53ba3e3a12f734ed7127704ff9a83361e7cc6f9a0f0b3e2b56d9868a76b9                # [win32]

  url: https://cmake.org/files/v{{ major_minor }}/cmake-{{ version }}-win64-x64.zip       # [win64]
  fn: cmake-{{ version }}-win64-x64.zip                                                   # [win64]
  sha256: 659ecb8207e1266786188c7eaf45308458ba5f719c985970f6f55ec0b5a96746                # [win64]

  patches:
    # This patch is already upstream
    # Reference: https://gitlab.kitware.com/cmake/cmake/merge_requests/361.patch
    - FindBoost-Add-support-for-1.63.patch  # [not win]
    - FindBoost-Add-support-for-1.63-win.patch  # [win]
  
build:
  number: 4
  detect_binary_files_with_prefix: true

requirements:
  build:             # [unix]
    - toolchain      # [unix]
    - bzip2 1.0.*    # [unix]
    - curl           # [unix]
    - expat          # [unix]
    - jsoncpp        # [unix]
    - libarchive     # [unix]
    - ncurses 5.9*   # [unix]
    - xz 5.2.*       # [unix]
    - zlib 1.2.*     # [unix]
    - libuv          # [unix]

  run:
    - bzip2 1.0.*    # [unix]
    - curl           # [unix]
    - expat          # [unix]
    - jsoncpp        # [unix]
    - libarchive     # [unix]
    - ncurses 5.9*   # [unix]
    - xz 5.2.*       # [unix]
    - zlib 1.2.*     # [unix]
    - libuv          # [unix]
    - vs2013_runtime  # [win]

test:
  files:
    - SSLTest.cmake
  commands:
    - cmake --version
    - cmake -V -P SSLTest.cmake

about:
  home: http://www.cmake.org/
  license: BSD 3-clause
  license_family: BSD
  summary: CMake is an extensible, open-source system that manages the build process

extra:
  recipe-maintainers:
    - blowekamp
    - groutr
    - jakirkham
    - ocefpaf
    - msarahan
    - scopatz
    - tadeu
