{% set version = "3.11.0" %}
{% set major_minor = '.'.join(version.split(".")[:2]) %}

package:
  name: cmake
  version: {{ version }}

source:
  url: https://cmake.org/files/v{{ major_minor }}/cmake-{{ version }}.tar.gz
  fn: cmake-{{ version }}.tar.gz
  sha256: c313bee371d4d255be2b4e96fd59b11d58bc550a7c78c021444ae565709a656b

build:
  number: 0
  msvc_compiler: 14.0

requirements:
  build:
    - toolchain
    - bzip2 1.0.*  # [unix]
    - curl >=7.44.0,<8  # [unix]
    - expat 2.2.*  # [unix]
    - ncurses 5.9*  # [unix]
    - xz 5.2.*  # [unix]
    - zlib 1.2.11  # [unix]
    - libuv  # [unix]
    - rhash  # [unix]

  run:
    - bzip2 1.0.*  # [unix]
    - curl >=7.44.0,<8  # [unix]
    - expat 2.2.*  # [unix]
    - ncurses 5.9*  # [unix]
    - xz 5.2.*  # [unix]
    - zlib 1.2.11  # [unix]
    - libuv  # [unix]
    - rhash  # [unix]
    - vs2015_runtime  # [win]

test:
  files:
    - SSLTest.cmake
  commands:
    - cmake --version
    - cmake -V -P SSLTest.cmake
    - ctest --version
    - cpack --version

about:
  home: http://www.cmake.org/
  license: BSD 3-clause
  license_family: BSD
  summary: CMake is an extensible, open-source system that manages the build process

extra:
  recipe-maintainers:
    - blowekamp
    - groutr
    - jakirkham
    - jschueller
    - ocefpaf
    - msarahan
    - scopatz
    - tadeu
